/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FormwatchImport } from './routes/formwatch'
import { Route as FormstateImport } from './routes/formstate'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FormwatchRoute = FormwatchImport.update({
  id: '/formwatch',
  path: '/formwatch',
  getParentRoute: () => rootRoute,
} as any)

const FormstateRoute = FormstateImport.update({
  id: '/formstate',
  path: '/formstate',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/formstate': {
      id: '/formstate'
      path: '/formstate'
      fullPath: '/formstate'
      preLoaderRoute: typeof FormstateImport
      parentRoute: typeof rootRoute
    }
    '/formwatch': {
      id: '/formwatch'
      path: '/formwatch'
      fullPath: '/formwatch'
      preLoaderRoute: typeof FormwatchImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formstate': typeof FormstateRoute
  '/formwatch': typeof FormwatchRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formstate': typeof FormstateRoute
  '/formwatch': typeof FormwatchRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/formstate': typeof FormstateRoute
  '/formwatch': typeof FormwatchRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/formstate' | '/formwatch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formstate' | '/formwatch'
  id: '__root__' | '/' | '/formstate' | '/formwatch'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormstateRoute: typeof FormstateRoute
  FormwatchRoute: typeof FormwatchRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormstateRoute: FormstateRoute,
  FormwatchRoute: FormwatchRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/formstate",
        "/formwatch"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/formstate": {
      "filePath": "formstate.tsx"
    },
    "/formwatch": {
      "filePath": "formwatch.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
